/// Schema Therapy Data - Part 2 (Remaining 9 schemas)
/// Domains 3, 4, and 5

import 'package:flutter/material.dart';
import 'schema_therapy_data.dart';

/// Extended schemas list - Part 2
class SchemaTherapyDatabasePart2 {
  static const List<SchemaTherapySchema> remainingSchemas = [
    // Domain 3: Impaired Limits (2 schemas)
    SchemaTherapySchema(
      id: 10,
      nameEn: 'Entitlement',
      nameTr: 'Hak Sahibi Olma',
      domain: SchemaDomain.impairedLimits,
      descriptionEn: 'Belief that you are special and should not have to follow rules.',
      descriptionTr: 'Özel olduğunuz ve kurallara uymanız gerekmediği inancı.',
      childhoodOriginEn: 'Excessive indulgence, lack of limits, or special treatment.',
      childhoodOriginTr: 'Aşırı hoşlanma, sınır eksikliği veya özel muamele.',
      effectsEn: ['Difficulty with authority', 'Impulsivity', 'Lack of empathy', 'Relationship conflicts'],
      effectsTr: ['Otorite ile zorluk', 'Dürtüsellik', 'Empati eksikliği', 'İlişki çatışmaları'],
      healingApproachEn: 'Develop empathy, learn consequences, practice self-control.',
      healingApproachTr: 'Empati geliştirin, sonuçları öğrenin, öz kontrol uygulayın.',
      difficultyToHeal: 4,
      icon: Icons.sentiment_very_satisfied,
      color: const Color(0xFFFFB300),
    ),
    SchemaTherapySchema(
      id: 11,
      nameEn: 'Insufficient Self-Control',
      nameTr: 'Yetersiz Öz Kontrol',
      domain: SchemaDomain.impairedLimits,
      descriptionEn: 'Difficulty controlling impulses and tolerating discomfort.',
      descriptionTr: 'Dürtüleri kontrol etme ve rahatsızlığa katlanma zorluğu.',
      childhoodOriginEn: 'Lack of discipline, excessive gratification, or chaotic environment.',
      childhoodOriginTr: 'Disiplin eksikliği, aşırı tatmin veya kaotik ortam.',
      effectsEn: ['Impulsive behavior', 'Difficulty delaying gratification', 'Substance abuse risk', 'Relationship problems'],
      effectsTr: ['Dürtüsel davranış', 'Tatmini erteleme zorluğu', 'Madde kötüye kullanım riski', 'İlişki sorunları'],
      healingApproachEn: 'Build distress tolerance, develop coping skills, practice delayed gratification.',
      healingApproachTr: 'Sıkıntı toleransı geliştirin, başa çıkma becerilerini geliştirin.',
      difficultyToHeal: 3,
      icon: Icons.psychology,
      color: const Color(0xFF6A1B9A),
    ),
    // Domain 4: Other-Directedness (3 schemas)
    SchemaTherapySchema(
      id: 12,
      nameEn: 'Subjugation',
      nameTr: 'Teslim Olma',
      domain: SchemaDomain.otherDirectedness,
      descriptionEn: 'Suppression of your own needs and emotions to avoid rejection.',
      descriptionTr: 'Reddedilmekten kaçınmak için kendi ihtiyaçlarınızı ve duygularınızı bastırma.',
      childhoodOriginEn: 'Controlling or punitive parents, conditional love.',
      childhoodOriginTr: 'Kontrol edici veya cezalandırıcı ebeveynler, koşullu sevgi.',
      effectsEn: ['Resentment', 'Difficulty expressing needs', 'Powerlessness', 'Passive-aggressive behavior'],
      effectsTr: ['Kin', 'İhtiyaçları ifade etme zorluğu', 'Güçsüzlük', 'Pasif-agresif davranış'],
      healingApproachEn: 'Assert boundaries, express needs, process anger.',
      healingApproachTr: 'Sınırları belirleyin, ihtiyaçları ifade edin, öfkeyi işleyin.',
      difficultyToHeal: 2,
      icon: Icons.lock,
      color: const Color(0xFF00838F),
    ),
    SchemaTherapySchema(
      id: 13,
      nameEn: 'Self-Sacrifice',
      nameTr: 'Kendini Feda Etme',
      domain: SchemaDomain.otherDirectedness,
      descriptionEn: 'Excessive focus on meeting others\' needs at the expense of your own.',
      descriptionTr: 'Başkalarının ihtiyaçlarını karşılamaya aşırı odaklanma.',
      childhoodOriginEn: 'Parentified child, family responsibility, modeling by parents.',
      childhoodOriginTr: 'Ebeveyn rolü alan çocuk, aile sorumluluğu.',
      effectsEn: ['Burnout', 'Resentment', 'Neglect of own needs', 'Exhaustion'],
      effectsTr: ['Tükenmişlik', 'Kin', 'Kendi ihtiyaçları ihmal', 'Yorgunluk'],
      healingApproachEn: 'Set boundaries, prioritize self-care, learn to say no.',
      healingApproachTr: 'Sınırlar belirleyin, öz bakımı önceliklendirin, hayır demesini öğrenin.',
      difficultyToHeal: 2,
      icon: Icons.volunteer_activism,
      color: const Color(0xFF1565C0),
    ),
    SchemaTherapySchema(
      id: 14,
      nameEn: 'Approval-Seeking',
      nameTr: 'Onay Arama',
      domain: SchemaDomain.otherDirectedness,
      descriptionEn: 'Excessive need for approval and recognition from others.',
      descriptionTr: 'Başkalarından onay ve tanınma konusunda aşırı ihtiyaç.',
      childhoodOriginEn: 'Conditional love based on achievement or appearance.',
      childhoodOriginTr: 'Başarı veya görünüşe dayalı koşullu sevgi.',
      effectsEn: ['Lack of authentic self', 'Perfectionism', 'Anxiety about judgment', 'Superficial relationships'],
      effectsTr: ['Gerçek benlik eksikliği', 'Mükemmeliyetçilik', 'Yargılanma kaygısı', 'Yüzeysel ilişkiler'],
      healingApproachEn: 'Develop authentic self, practice self-validation, challenge perfectionism.',
      healingApproachTr: 'Gerçek benlik geliştirin, öz doğrulama uygulayın.',
      difficultyToHeal: 3,
      icon: Icons.star,
      color: const Color(0xFFE65100),
    ),
    // Domain 5: Over-vigilance & Inhibition (4 schemas)
    SchemaTherapySchema(
      id: 15,
      nameEn: 'Negativity/Pessimism',
      nameTr: 'Olumsuzluk/Kötümserlik',
      domain: SchemaDomain.overVigilanceInhibition,
      descriptionEn: 'Focus on negative aspects of life and expectation of bad outcomes.',
      descriptionTr: 'Hayatın olumsuz yönlerine odaklanma ve kötü sonuçlar bekleme.',
      childhoodOriginEn: 'Pessimistic parents, chronic stress, or actual adversity.',
      childhoodOriginTr: 'Kötümser ebeveynler, kronik stres veya gerçek zorluklar.',
      effectsEn: ['Chronic anxiety', 'Rumination', 'Indecisiveness', 'Depression'],
      effectsTr: ['Kronik kaygı', 'Düşünüp taşınma', 'Kararsızlık', 'Depresyon'],
      healingApproachEn: 'Cognitive restructuring, mindfulness, behavioral activation.',
      healingApproachTr: 'Bilişsel yeniden yapılandırma, farkındalık, davranışsal aktivasyon.',
      difficultyToHeal: 3,
      icon: Icons.cloud,
      color: const Color(0xFF424242),
    ),
    SchemaTherapySchema(
      id: 16,
      nameEn: 'Emotional Inhibition',
      nameTr: 'Duygusal Bastırma',
      domain: SchemaDomain.overVigilanceInhibition,
      descriptionEn: 'Suppression of emotions to maintain control and avoid disapproval.',
      descriptionTr: 'Kontrol sağlamak ve onay almamak için duyguları bastırma.',
      childhoodOriginEn: 'Shaming for emotions, strict family rules, emotional coldness.',
      childhoodOriginTr: 'Duygulardan utandırma, katı aile kuralları, duygusal soğukluk.',
      effectsEn: ['Emotional numbness', 'Difficulty with intimacy', 'Stress-related illness', 'Relationship distance'],
      effectsTr: ['Duygusal uyuşukluk', 'Yakınlıkta zorluk', 'Stres hastalıkları', 'İlişki mesafesi'],
      healingApproachEn: 'Emotional expression exercises, therapy, gradual vulnerability.',
      healingApproachTr: 'Duygusal ifade alıştırmaları, terapı, kademeli açılık.',
      difficultyToHeal: 3,
      icon: Icons.sentiment_neutral,
      color: const Color(0xFF455A64),
    ),
    SchemaTherapySchema(
      id: 17,
      nameEn: 'Unrelenting Standards',
      nameTr: 'Tükenmeyen Standartlar',
      domain: SchemaDomain.overVigilanceInhibition,
      descriptionEn: 'Pursuit of perfection and extremely high standards for yourself.',
      descriptionTr: 'Mükemmellik arayışı ve kendiniz için son derece yüksek standartlar.',
      childhoodOriginEn: 'High parental expectations, perfectionist modeling.',
      childhoodOriginTr: 'Yüksek ebeveyn beklentileri, mükemmeliyetçi modelleme.',
      effectsEn: ['Chronic stress', 'Burnout', 'Difficulty relaxing', 'Relationship strain'],
      effectsTr: ['Kronik stres', 'Tükenmişlik', 'Rahatlamada zorluk', 'İlişki gerginliği'],
      healingApproachEn: 'Challenge perfectionism, practice self-compassion, set realistic goals.',
      healingApproachTr: 'Mükemmeliyetçiliğe meydan okuyun, öz şefkat uygulayın.',
      difficultyToHeal: 2,
      icon: Icons.check_circle,
      color: const Color(0xFF1B5E20),
    ),
    SchemaTherapySchema(
      id: 18,
      nameEn: 'Punitiveness',
      nameTr: 'Cezalandırıcılık',
      domain: SchemaDomain.overVigilanceInhibition,
      descriptionEn: 'Belief that mistakes should be severely punished, not forgiven.',
      descriptionTr: 'Hataların affedilmemesi gerektiği, cezalandırılması gerektiği inancı.',
      childhoodOriginEn: 'Harsh punishment, rigid moral standards, intolerant parents.',
      childhoodOriginTr: 'Sert ceza, katı ahlaki standartlar, hoşgörüsüz ebeveynler.',
      effectsEn: ['Self-criticism', 'Guilt and shame', 'Intolerance of others', 'Difficulty forgiving'],
      effectsTr: ['Öz eleştiri', 'Suçluluk ve utanç', 'Başkalarına hoşgörüsüzlük', 'Affetme zorluğu'],
      healingApproachEn: 'Develop self-compassion, practice forgiveness, challenge rigid beliefs.',
      healingApproachTr: 'Öz şefkat geliştirin, affetmeyi uygulayın, katı inançlara meydan okuyun.',
      difficultyToHeal: 3,
      icon: Icons.gavel,
      color: const Color(0xFF880E4F),
    ),
  ];
}

